version: '3.8'

services:
  db:
    container_name: postgres
    image: postgres:17
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  redis_users:
    container_name: redis_users
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend

  app:
    image: fastapi_games
    stdin_open: true
    tty: true
    env_file:
      - .env_container
    environment:
      POSTGRES_USER: ${DB_USER}
      DB_HOST: db
      API_REDIS_HOST: redis_users
    ports:
      - "8000:8000"
      - "5678:5678"
    depends_on:
      - db
      - redis_users
    networks:
      - backend
    command:
      sh -c "
      alembic upgrade head &&
      python -m pip install debugpy &&
      python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 --wait-for-client 
      -m uvicorn main:app --host 0.0.0.0 --port 8000
      "


volumes:
  postgres_data:
  redis_data:

networks:
  backend:
    driver: bridge