"""create cover

Revision ID: ad47d1222ab8
Revises: 837907086e95
Create Date: 2025-02-08 20:21:53.808899

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "ad47d1222ab8"
down_revision: Union[str, None] = "837907086e95"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cover",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["game_id"], ["game.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("game", sa.Column("cover_id", sa.Uuid(), nullable=False))
    op.create_foreign_key(
        None, "game", "cover", ["cover_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "game", type_="foreignkey")
    op.drop_column("game", "cover_id")
    op.drop_table("cover")
    # ### end Alembic commands ###
