"""game_change

Revision ID: 7460f8e2e61c
Revises: 986587ba298c
Create Date: 2025-02-24 16:30:34.068551

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7460f8e2e61c"
down_revision: Union[str, None] = "986587ba298c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_game_name"), "game", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_game_name"), table_name="game")
    # ### end Alembic commands ###
