"""columns_changes

Revision ID: 9f169f38d790
Revises: ad47d1222ab8
Create Date: 2025-02-12 18:07:36.049393

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9f169f38d790"
down_revision: Union[str, None] = "ad47d1222ab8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("game_cover_id_fkey", "game", type_="foreignkey")
    op.create_foreign_key(None, "game", "cover", ["cover_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "game", type_="foreignkey")
    op.create_foreign_key(
        "game_cover_id_fkey", "game", "cover", ["cover_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###
